---
- name: Config Web VM with Docker
  hosts: webservers
  become: true
  tasks:

    - name: Uninstall apache if needed
      ansible.builtin.apt:
        update_cache: yes
        name: apache2
        state: absent

    - name: Install Docker package
      ansible.builtin.apt:
        update_cache: yes
        name: docker.io
        state: present

    - name: Ensure python3-venv is installed
      ansible.builtin.apt:
        name: python3-venv
        state: present

    - name: Ensure pip3 is installed
      ansible.builtin.apt:
        name: python3-pip
        state: present

    - name: Create a virtual environment
      ansible.builtin.command:
        cmd: python3 -m venv /opt/myenv
        creates: /opt/myenv/bin/activate

    - name: Install Docker python module in virtual environment
      ansible.builtin.command:
        cmd: /opt/myenv/bin/pip install docker
      environment:
        PATH: /opt/myenv/bin:{{ ansible_env.PATH }}

    - name: Set Python interpreter to use virtual environment
      set_fact:
        ansible_python_interpreter: /opt/myenv/bin/python

    - name: Download and launch a Docker web container
      community.docker.docker_container:
        name: dvwa
        image: cyberxsecurity/dvwa
        state: started
        published_ports: 80:80

    - name: Enable Docker service
      ansible.builtin.systemd:
        name: docker
        enabled: yes
